### ISSUE TITLE
How to stop where i want 

### ISSUE THREAD

**Issue by royalnavneet** [marcolago/Spin-Two-Three#2]
First, thanks for a great slider script, Its beautiful and just what I have been looking for my project. I am, however looking for a solution through which I can pre-determine the image on which this slider will sstop. 
Actually, this needs to be the part of a short game, where profile image of all participating users are being spinned and the user  on which this will stop will be the winner. I'm wanting to pre-determine the user who will win since that's calculated based on an algorithm and not randomly like it happens in your script at the  moment. 
I have tried looking at   the various functions that you have outhere but there has been no success. 
Can you suggest a solution? I'll be highly obliged if you can.
Thanks yet again and I'm counting on you for this mate.

**Comment by marcolago** [comment]
Hi.
Thanks for the appreciation.

This script was designed to be absolutely randomic, just because to predetermine the final image per slot need some complex calculations to set speed and time of the wheels.

It should be possible to know when an image is the actual one checking and stopping the wheel, but the animation will not be as smooth as you imagine.
But I think it will be pretty hard because Spin Two Three was not designed with this feature in mind.

Otherwise you should set the starting position and the speed for every wheel and let them to naturally stop on the winner user. I think it could be done with some simple calculations (or in an empiric way).

I hope these suggestions will be helpful.
Let me know if you need some support.
